/* Auto-generated by: https://github.com/pmndrs/gltfjsx */

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function AliceModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('../../../aliceModel.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-2.34, 0, -0.57]} rotation={[0, 1, 0]} scale={0.36}>
        <mesh geometry={nodes.Sphere040.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Sphere040_1.geometry} material={materials.Skin} />
        <mesh geometry={nodes.Sphere040_2.geometry} material={materials.Black} />
        <mesh geometry={nodes.Sphere040_3.geometry} material={materials.lips} />
        <mesh geometry={nodes.Sphere040_4.geometry} material={materials.Hair} />
        <mesh geometry={nodes.Sphere040_5.geometry} material={materials.White} />
        <mesh geometry={nodes.Sphere040_6.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Sphere040_7.geometry} material={materials.Green} />
      </group>
    </group>
  )
};

useGLTF.preload('../../../aliceModel.glb');
