/* Auto-generated by: https://github.com/pmndrs/gltfjsx */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function AliceTree({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../3D-models/aliceTree.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0, -0.1, 0]}
        rotation={[1.59, 0, -0.1]}
        scale={0.4}
      >
        <mesh
          geometry={nodes.Text012.geometry}
          material={materials.LightBrown}
        />
        <mesh geometry={nodes.Text012_1.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Text012_2.geometry} material={materials.Green} />
        <mesh geometry={nodes.Text012_3.geometry} material={materials.Skin} />
        <mesh geometry={nodes.Text012_4.geometry} material={materials.Black} />
        <mesh geometry={nodes.Text012_5.geometry} material={materials.lips} />
        <mesh geometry={nodes.Text012_6.geometry} material={materials.Hair} />
        <mesh geometry={nodes.Text012_7.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Text012_8.geometry} material={materials.White} />
      </group>
    </group>
  );
}

useGLTF.preload("../../../3D-models/aliceTree.glb");
