/* Auto-generated by: https://github.com/pmndrs/gltfjsx */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Cards({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../3D-models/cards.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[23, -1, -25]}
        rotation={[0, 3, 0]}
        scale={[0.1, 0.07, 0.1]}
      >
        <mesh
          geometry={nodes.Cylinder011.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder011_1.geometry}
          material={materials.White}
        />
        <mesh
          geometry={nodes.Cylinder011_2.geometry}
          material={materials.Red}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../3D-models/cards.glb");
