/* Auto-generated by: https://github.com/pmndrs/gltfjsx */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Caterpillar({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../3D-models/caterpillar.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-15, 8, -20]}
        rotation={[4.3, 2.3, .2]}
        scale={0.49}
      >
        <mesh geometry={nodes.Text002_1.geometry} material={materials.Green} />
        <mesh
          geometry={nodes.Text002_2.geometry}
          material={materials.DarkRed}
        />
        <mesh
          geometry={nodes.Text002_3.geometry}
          material={materials.DarkBeige}
        />
        <mesh
          geometry={nodes.Text002_4.geometry}
          material={materials.LightBeige}
        />
        <mesh
          geometry={nodes.Text002_5.geometry}
          material={materials.DarkBlue}
        />
        <mesh
          geometry={nodes.Text002_6.geometry}
          material={materials.LightBlue}
        />
        <mesh geometry={nodes.Text002_7.geometry} material={materials.Pink} />
        <mesh geometry={nodes.Text002_8.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.Text002_9.geometry} material={materials.Black} />
        <mesh geometry={nodes.Text002_10.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Text002_11.geometry} material={materials.PinkK} />
        <mesh
          geometry={nodes.Text002_12.geometry}
          material={materials.Purple}
        />
        <mesh
          geometry={nodes.Text002_13.geometry}
          material={materials.LightBBlue}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../3D-models/caterpillar.glb");
