/* Auto-generated by: https://github.com/pmndrs/gltfjsx */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Zzz({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../3D-models/zzz.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials["Material.001"]}
        position={[-2.5, 1.5, -0.8]}
        rotation={[Math.PI / 2, 0, 0.3]}
        scale={0.6}
      />
    </group>
  );
}

useGLTF.preload("../../../3D-models/zzz.glb");
