/* Auto-generated by: https://github.com/pmndrs/gltfjsx */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function AliceBottle({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "../../../../../3D-models/aliceBottle.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 10, 0]} rotation={[0, 2.5, 0]} scale={[4, 4.19, 4]}>
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Cylinder003_1.geometry}
          material={materials.Skin}
        />
        <mesh
          geometry={nodes.Cylinder003_2.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder003_3.geometry}
          material={materials.lips}
        />
        <mesh
          geometry={nodes.Cylinder003_4.geometry}
          material={materials.Hair}
        />
        <mesh
          geometry={nodes.Cylinder003_5.geometry}
          material={materials.Blue}
        />
        <mesh
          geometry={nodes.Cylinder003_6.geometry}
          material={materials.White}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../../../3D-models/aliceBottle.glb");
